name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ../../TodoAPI/TodoAPI.csproj

    - name: Build the project
      run: dotnet build --configuration Release ../../TodoAPI/TodoAPI.csproj

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./publish ../../TodoAPI/TodoAPI.csproj

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./publish
        file: ../../TodoAPI/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/todoapi:latest
